# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ContractGo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'TPKeyboardAvoiding'
  pod 'SDWebImage'
  #pod 'ReachabilitySwift'
  pod 'Reachability'
  pod 'SwiftyJSON'
  pod 'MBProgressHUD'
  pod 'SVProgressHUD'

end
